-- Create Todos Table
create table todos (
  id bigint generated by default as identity primary key,
  title text not null,
  done boolean not null default false,
  created_at timestamptz not null default now()
);

-- Enable Row Level Security
alter table todos enable row level security;

-- Create Policy for Anonymous Access (DEMO ONLY)
-- Warning: This policy allows anyone with the anon key to read/write all rows.
-- In a real app, you would use 'auth.uid() = user_id' policies.

create policy "Enable access for all users" on todos
  for all using (true) with check (true);
